export type { NoteInput, ContextNode, ContextPackage } from './types.js'
export { bfsTraversal } from './graph-traversal.js'
export { assembleContext } from './context-assembler.js'
export { singleNotePrompt, graphAwarePrompt } from './prompt-structurer.js'
export type { NoteResult, SearchResult, BacklinkResult, VaultReader } from './vault-reader.js'
